Group members design changes
BeCauseEco/components pull request #74
Opened 2024-10-15 08:51 UTC by JovanBosnic

2024-10-15 13:43 UTC, ralobecause requested changes

2024-10-15 13:43 UTC, ralobecause commented on src/Icon/Icon.tsx
> +  point?: boolean
Maybe there are some cases I'm not aware of 🤔 To me, this should not be possible to change within the component.

Pointers are used for something being clickable for an action. An icon shouldn't have that functionality. Instead whatever behavior that requires this to be possible should wrap the Icon and achieve it in that way.

The Icon knows nothing else but what it, how big and what color.

Is there a case here I didn't think of? Can you achieve this without this addition?

2024-10-15 13:43 UTC, ralobecause commented on src/InputButton/InputButton.tsx
> +            colorOutline={props.outlineColor ?? [props.color, 700]}
Hmm being able to do this will introduce possibility to create inconsistencies with our buttons style wise. I'm not sure design would be onboard this, else I would push back

When should the outlineColor and colorBackgroundHover ever be able to be different?

2024-10-15 13:43 UTC, ralobecause commented on src/InputCheckbox/InputCheckbox.tsx
> +          {icon}
Is it aligned with design that they want to introduce the standard of having icons in the button text? And that the gap should always be 5px?

As an alternative this could be achieve without this addition. However then we're introducing some custom styling to the button and if we want to copy this, we can't guarantee the styling to be the same.

```
const Container = styled.div`
  display: flex;
  flex-direction: row;
  gap: 5px;
  align-items: center;
`

<Text size={ESize.Small} color={[EColor.Black, 700]} wrap emphasize>
  <Container>
    <Icon name="home" size={ESize.Medium} color={[EColor.Black, 700]} />
    {labelText}
  </Container>
</Text>
```

So I think it's a good addition IF design can confirm the standard (and the gap) 👍

2024-10-15 13:43 UTC, ralobecause commented on src/InputCombobox/InputCombobox.tsx
> +              items.length > 9 && (
Should we introduce a const variable for 9? I would not be sure why specifically 9 here

2024-10-15 13:43 UTC, ralobecause commented on src/InputCombobox/InputCombobox.tsx
> +                    color={[colorButtonForeground, 1000]}
Are you sure of 1000 here and further below? It's a very 'harsh' color spec

2024-10-15 13:43 UTC, ralobecause commented on src/InputCombobox/InputComboboxItem.tsx
> +  icon,
Is this so that we can display the country flags?

It seems like a one-off to have icons next to the label. We can always add it inside the label if it's a one-off.

Would be good to align that with design and confirm whether it's a new standard or one-off.

2024-10-15 13:43 UTC, ralobecause commented on src/InputCombobox/InputCombobox.tsx
> +    return (
This here is nice 🔥 Great addition

2024-10-15 14:11 UTC, JovanBosnic commented on src/InputCombobox/InputComboboxItem.tsx
> +  icon,
Yes but problem is that we're using it from third party application, we can't use new Icon component with name="home":

import { CircleFlag } from "react-circle-flags"
  return <CircleFlag loading="lazy" countryCode={alpha2.toLowerCase()} height="20" />

So for now I just passed the icon as ReactNode and I am rendering it next to option.

2024-10-15 14:12 UTC, JovanBosnic commented on src/InputCombobox/InputCombobox.tsx
> +                    color={[colorButtonForeground, 1000]}
Well it's per latest design that Matas sent me:
![image](https://github.com/user-attachments/assets/093596f8-8c58-4fb9-88a8-25b93bfc6eaa)

2024-10-15 14:13 UTC, JovanBosnic commented on src/InputCombobox/InputCombobox.tsx
> +              items.length > 9 && (
Again it's per new design:
![image](https://github.com/user-attachments/assets/debb6bf2-bcec-4230-8c10-0955df8a42f8)

2024-10-15 14:15 UTC, JovanBosnic commented on src/InputCheckbox/InputCheckbox.tsx
> +          {icon}
No, this is something that I've 'freelanced' :D

It's fine about the gap, but for Icon I am not sure as I metnioned in previous comments I am reusing existing country flag component that's coming from external package.

2024-10-15 14:23 UTC, JovanBosnic commented on src/InputButton/InputButton.tsx
> +            colorOutline={props.outlineColor ?? [props.color, 700]}
Yes, let me show you an examples.

Regular input button with regular hover (a bit darker):
![image](https://github.com/user-attachments/assets/99a047c2-705c-4f14-a3fe-557bd902f876)


Input button on selector as per new design:
![image](https://github.com/user-attachments/assets/ceac909e-cf85-44c9-b2b0-5e255b5ea3dc)

You see color and border color are different:
![image](https://github.com/user-attachments/assets/bf3fdce6-95f5-40ed-a410-2b3134157fd2)

2024-10-15 14:23 UTC, JovanBosnic commented on src/Icon/Icon.tsx
> +  point?: boolean
You're right I'll wrap it in button component :D

2024-10-16 13:44 UTC, acaSimic24 approved these changes

2024-10-16 13:50 UTC, ralobecause approved these changes

2024-10-16 13:52 UTC, merged